//忘记密码
export const PERFORM_FORGET_ACTION = 'PERFORM_FORGET_ACTION';
export const RECEIVE_FORGET_ACTION = 'RECEIVE_FORGET_ACTION';
export const RECEIVE_FORGET_ERROR_ACTION = 'RECEIVE_FORGET_ERROR_ACTION';

//登陆
export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN_ACTION';
export const RECEIVE_LOGIN_ACTION = 'RECEIVE_LOGIN_ACTION';
export const RECEIVE_LOGIN_ERROR_ACTION = 'RECEIVE_LOGIN_ERROR_ACTION';

//网络连接
export const NETWORK_STATE_ONLINE = 'NETWORK_STATE_ONLINE'
export const NETWORK_STATE_OFFLINE = 'NETWORK_STATE_OFFLINE'

//列表加载更多，刷新
export const GET_PRODUCT_LIST_SUCC = 'GET_PRODUCT_LIST_SUCC'
export const CHANGE_PRODUCT_LIST_REFRESHING = 'CHANGE_PRODUCT_LIST_REFRESHING'
export const CHANGE_PRODUCT_LIST_LOADINGMORE = 'CHANGE_PRODUCT_LIST_LOADINGMORE'
